
<?php

global $ry, $sqlConnect;

$query = mysqli_query($sqlConnect, "SELECT * FROM products");

$result = mysqli_fetch_all($query, MYSQLI_ASSOC);

?>

<?php if (mysqli_num_rows($query) > 0) {?>
  <?php foreach ($result as $key) {?>
<div class="row"><div class="card" style="width: 18rem;">
<img class="card-img-top" src="<?php echo $ry['site_url']; ?>/<?php echo $key['image']; ?>" alt="Card image cap">
<div class="card-body" style="background-color:black;">
  <h5 class="card-title"><?php echo $key['name']; ?></h5>
  <p class="card-text">NPR <?php echo $key['price']; ?></p>
  <p class="card-text"><input type="text" value="1" id="count_<?php echo $key['id']?>"></p>
  <a href="javascript:void(0)" onclick="var count = document.getElementById('count_<?php echo $key['id']?>').value;cart('add','<?php echo $key['id'];?>',count)" class="btn btn-primary">Add To Cart</a>
</div>
</div>
<?php }?>
</div>
<?php } else {?>
product is empty
  <?php }?>